//
//  Constants.swift
//  PingDavinciPlugin
//
//  Copyright (c) 2024 - 2026 Ping Identity Corporation. All rights reserved.
//
//  This software may be modified and distributed under the terms
//  of the MIT license. See the LICENSE file for details.
//

/// Represents various constants used in Davinci requests and flows.
public enum Constants {
    public static let actionKey = "actionKey"
    public static let formData = "formData"
    public static let type = "type"
    public static let inputType = "inputType"
    public static let key = "key"
    public static let label = "label"
    public static let value = "value"
    public static let form = "form"
    public static let components = "components"
    public static let fields = "fields"
    public static let eventType = "eventType"
    public static let name = "name"
    public static let id = "id"
    public static let data = "data"
    public static let eventName = "eventName"
    public static let parameters = "parameters"
    public static let description = "description"
    public static let category = "category"
    public static let next = "next"
    public static let href = "href"
    public static let _self = "self"
    public static let _links = "_links"
    public static let message = "message"
    public static let status = "status"
    public static let authorizeResponse = "authorizeResponse"
    public static let code = "code"
    public static let code_1999 = 1999
    public static let FAILED = "FAILED"
    public static let TEXT = "TEXT"
    public static let PASSWORD =  "PASSWORD"
    public static let PASSWORD_VERIFY = "PASSWORD_VERIFY"
    public static let SUBMIT_BUTTON = "SUBMIT_BUTTON"
    public static let FLOW_BUTTON = "FLOW_BUTTON"
    public static let FLOW_LINK = "FLOW_LINK"
    public static let ACTION = "ACTION"
    public static let LABEL = "LABEL"
    public static let DROPDOWN = "DROPDOWN"
    public static let RADIO = "RADIO"
    public static let COMBOBOX = "COMBOBOX"
    public static let CHECKBOX = "CHECKBOX"
    public static let SINGLE_SELECT = "SINGLE_SELECT"
    public static let MULTI_SELECT = "MULTI_SELECT"
    public static let error = "error"
    public static let connectorId = "connectorId"
    public static let capabilityName = "capabilityName"
    public static let requestTimedOut = "requestTimedOut"
    public static let pingOneAuthenticationConnector = "pingOneAuthenticationConnector"
    public static let returnSuccessResponseRedirect = "returnSuccessResponseRedirect"
    public static let setSession = "setSession"
    public static let location = "Location"
    public static let content = "content"
    public static let required = "required"
    public static let options = "options"
    public static let passwordPolicy = "passwordPolicy"
    public static let validation = "validation"
    public static let regex = "regex"
    public static let errorMessage = "errorMessage"
    public static let SOCIAL_LOGIN_BUTTON = "SOCIAL_LOGIN_BUTTON"
    public static let idpEnabled = "idpEnabled"
    public static let idpId = "idpId"
    public static let idpType = "idpType"
    public static let links = "links"
    public static let authenticate = "authenticate"
    public static let details = "details"
    public static let target = "target"
    public static let innerError = "innerError"
    public static let statusCode = "statusCode"
    public static let rawResponse = "rawResponse"
    public static let unsatisfiedRequirements = "unsatisfiedRequirements"
    public static let GOOGLE = "GOOGLE"
    public static let FACEBOOK = "FACEBOOK"
    public static let APPLE = "APPLE"
    public static let devices = "devices"
    public static let DEVICE_REGISTRATION = "DEVICE_REGISTRATION"
    public static let DEVICE_AUTHENTICATION = "DEVICE_AUTHENTICATION"
    public static let PHONE_NUMBER = "PHONE_NUMBER"
    public static let submit = "submit"
    public static let countryCode = "countryCode"
    public static let phoneNumber = "phoneNumber"
    public static let defaultCountryCode = "defaultCountryCode"
    public static let validatePhoneNumber = "validatePhoneNumber"
    
    // MARK: - Polling & QR Code
    public static let POLLING = "POLLING"
    public static let QR_CODE = "QR_CODE"
    public static let pollInterval = "pollInterval"
    public static let pollRetries = "pollRetries"
    public static let pollChallengeStatus = "pollChallengeStatus"
    public static let challenge = "challenge"
    public static let isChallengeComplete = "isChallengeComplete"
    public static let rewindStateToLastRenderedUI = "rewindStateToLastRenderedUI"
    public static let rewindStateToSpecificRenderedUI = "rewindStateToSpecificRenderedUI"
    public static let interactionId = "interactionId"
    public static let fallbackText = "fallbackText"
    public static let base64Separator = "base64,"
    public static let pollingEventType = "polling"
    public static let pollingValueContinue = "continue"
    public static let pollingValueTimedOut = "timedOut"
    public static let pollingValueExpired = "expired"
    public static let pollingValueError = "error"
    public static let davinciConnectionsPathSegment = "/davinci/connections"
    public static let challengeStatusPathPrefix = "/davinci/user/credentials/challenge/"
    public static let challengeStatusPathSuffix = "/status"
}
