name: Build and Test

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        description: 'Slack Notifier Webhook'
        required: true
  
env:
  WORKSPACE: SampleApps/Ping.xcworkspace
  SCHEME: PingTestHost
  CONFIGURATION: Debug
  DESTINATION: platform=iOS Simulator,name=iPhone SE (3rd generation),OS=26.1
  XCODE_VERSION: '26.1.1'
  DERIVED_DATA_PATH: DerivedData

jobs:
  build-and-test:
    runs-on: macos-15-xlarge
    timeout-minutes: 40

    steps:
      # Clone the repo
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      # Set target Xcode version. For more details and options see:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app && /usr/bin/xcodebuild -version

      # # Cache DerivedData
      # - name: Cache DerivedData
      #   if: always()
      #   uses: actions/cache@v5
      #   with:
      #     path: ${{ env.DERIVED_DATA_PATH }}
      #     key: ${{ runner.os }}-derived-data-${{ env.XCODE_VERSION }}-${{ hashFiles('**/Podfile.lock', '**/*.pbxproj') }}
      #     restore-keys: |
      #       ${{ runner.os }}-derived-data-${{ env.XCODE_VERSION }}-

      # Cache Swift Packages
      - name: Cache Swift Packages
        if: always()
        uses: actions/cache@v5
        with:
          path: SourcePackages
          # Look for Package.resolved inside your workspace or project
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Install xcresultparser
      - name: Install xcresultparser
        run: |
          curl -LO https://github.com/a7ex/xcresultparser/releases/download/1.9.3/xcresultparser.zip
          unzip xcresultparser.zip
          # Fix: The binary is inside the 'product' folder
          chmod +x product/xcresultparser
          sudo mv product/xcresultparser /usr/local/bin/

      - name: Reset simulators
        run: |
          xcrun simctl shutdown all || true
          xcrun simctl erase all || true
          
      # List available simulators
      - name: List available simulators
        run: xcrun simctl list devices

      # Pre-boot the simulator to avoid timeouts during xcodebuild
      - name: Pre-boot Simulator
        run: |
          xcrun simctl bootstatus "iPhone SE (3rd generation)" -b || true

      # Build the SDK for testing
      - name: Build for testing
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
            -scheme "${{ env.SCHEME }}" \
            -workspace "${{ env.WORKSPACE }}" \
            -destination '${{ env.DESTINATION }}' \
            -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
            -clonedSourcePackagesDirPath SourcePackages \
            COMPILER_INDEX_STORE_ENABLE=NO | xcbeautify

      # Run the unit tests without building
      - name: Run unit tests
        run: |
          set -o pipefail
          xcodebuild test-without-building \
            -scheme "${{ env.SCHEME }}" \
            -workspace "${{ env.WORKSPACE }}" \
            -destination '${{ env.DESTINATION }}' \
            -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
            -resultBundlePath TestResults.xcresult \
            -parallel-testing-enabled NO \
            -parallel-testing-worker-count 1 \
            -retry-tests-on-failure | xcbeautify

      # # Run unit tests
      # - name: Run tests
      #   run: |
      #     set -o pipefail && xcodebuild test \
      #     -scheme ${{ env.SCHEME }} \
      #     -workspace ${{ env.WORKSPACE }} \
      #     -destination '${{ env.DESTINATION }}' \
      #     -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
      #     -clonedSourcePackagesDirPath SourcePackages \
      #     -parallel-testing-enabled NO \
      #     -retry-tests-on-failure \
      #     COMPILER_INDEX_STORE_ENABLE=NO \
      #     -resultBundlePath TestResults | xcbeautify

      #     # -configuration ${{ env.CONFIGURATION}} \
      #     # TEST_TARGET_SIGNING=YES \
      #     # -enableCodeCoverage YES \
      #     # -resultBundlePath TestResults \
      #     # -disable-concurrent-destination-testing \
      #     # -retry-tests-on-failure 
          
      # Upload xcresult for debugging purposes
      - name: Upload xcresult (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults.xcresult
          path: TestResults.xcresult

      # Convert test results to JUnit format
      - name: Convert Test Results to JUnit
        if: always()
        run: xcresultparser -o junit TestResults.xcresult > test-report.xml

      # Publish the test results
      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests results
          path: test-report.xml
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'false'
          reporter: java-junit
      
      # Send slack notification with result status
      - uses: 8398a7/action-slack@v3
        with:
          mention: 'stoyan.petrov'
          if_mention: 'failure,cancelled'
          fields: repo,author,eventName,message,job,pullRequest,took
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()